[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
counter = "0.6.0"
gcd = "2.3.0"
itertools = "0.13.0"
rand = "0.8.5"
regex = "1.11.1"
tokio = { version = "1.42.0", features = ["full"] }