[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
cached = "0.54.0"
counter = "0.6.0"
gcd = "2.3.0"
itertools = "0.13.0"
num = "0.4.3"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.11.1"
tokio = { version = "1.42.0", features = ["full"] }
